#!/bin/bash

PORTA=${PORTA:-port7}
PORTB=${PORTB:-port8}
PORTC=${PORTC:-port41}
PORTD=${PORTD:-port47}
BRIDGE=${BRIDGE:-swbridge}

MGMT_VLAN=4090
STREAM_VLAN=15

MC_GRP=239.255.1.3

function setup() {
  ip link add name ${BRIDGE} type bridge vlan_filtering 1 mcast_querier 1
  ip link set ${BRIDGE} up

  # port 1
  ip link set ${PORTA} master ${BRIDGE}
  ip link set ${PORTA} up

  # port 2
  ip link set ${PORTB} master ${BRIDGE}
  ip link set ${PORTB} up

  # setup multicast vids
  bridge vlan add vid ${STREAM_VLAN} dev ${PORTA}
  bridge vlan add vid ${STREAM_VLAN} dev ${PORTB}

  # setup multicast bridge
  bridge mdb add dev ${BRIDGE} port ${PORTA} grp ${MC_GRP} vid ${STREAM_VLAN}
  bridge mdb add dev ${BRIDGE} port ${PORTB} grp ${MC_GRP} vid ${STREAM_VLAN}
}

setup
